import { db } from '@/db';
import { diseases } from '@/db/schema';

async function main() {
    const sampleDiseases = [
        {
            diseaseName: 'Common Cold',
            medicineMeasures: 'Rest and fluids. Take paracetamol for symptoms. Use nasal decongestants.',
            fever: false,
            headache: true,
            cough: true,
            nausea: false,
            vomiting: false,
            chestPain: false,
            breathlessness: false,
            abdominalPain: false,
            soreThroat: true,
            runnyNose: true,
            bodyAches: true,
            sweating: false,
            createdAt: new Date('2024-01-10').toISOString(),
            updatedAt: new Date('2024-01-10').toISOString(),
        },
        {
            diseaseName: 'Influenza',
            medicineMeasures: 'Antiviral medications within 48 hours. Rest and increase fluid intake.',
            fever: true,
            headache: true,
            cough: true,
            nausea: true,
            vomiting: false,
            chestPain: false,
            breathlessness: false,
            abdominalPain: false,
            soreThroat: true,
            runnyNose: true,
            bodyAches: true,
            sweating: true,
            createdAt: new Date('2024-01-12').toISOString(),
            updatedAt: new Date('2024-01-12').toISOString(),
        },
        {
            diseaseName: 'Food Poisoning',
            medicineMeasures: 'Oral rehydration therapy. Avoid solid foods initially. Seek medical help if severe.',
            fever: false,
            headache: true,
            cough: false,
            nausea: true,
            vomiting: true,
            chestPain: false,
            breathlessness: false,
            abdominalPain: true,
            soreThroat: false,
            runnyNose: false,
            bodyAches: true,
            sweating: false,
            createdAt: new Date('2024-01-15').toISOString(),
            updatedAt: new Date('2024-01-15').toISOString(),
        },
        {
            diseaseName: 'Heart Attack',
            medicineMeasures: 'EMERGENCY: Call 911 immediately. Chew aspirin if not allergic. Do not drive yourself.',
            fever: false,
            headache: false,
            cough: false,
            nausea: true,
            vomiting: false,
            chestPain: true,
            breathlessness: true,
            abdominalPain: false,
            soreThroat: false,
            runnyNose: false,
            bodyAches: false,
            sweating: true,
            createdAt: new Date('2024-01-18').toISOString(),
            updatedAt: new Date('2024-01-18').toISOString(),
        },
        {
            diseaseName: 'Gastritis',
            medicineMeasures: 'Avoid spicy foods. Take antacids. Eat small frequent meals.',
            fever: false,
            headache: true,
            cough: false,
            nausea: true,
            vomiting: true,
            chestPain: false,
            breathlessness: false,
            abdominalPain: true,
            soreThroat: false,
            runnyNose: false,
            bodyAches: false,
            sweating: false,
            createdAt: new Date('2024-01-20').toISOString(),
            updatedAt: new Date('2024-01-20').toISOString(),
        },
        {
            diseaseName: 'Bronchitis',
            medicineMeasures: 'Rest and fluids. Use humidifier. Cough suppressants may help.',
            fever: false,
            headache: true,
            cough: true,
            nausea: false,
            vomiting: false,
            chestPain: false,
            breathlessness: true,
            abdominalPain: false,
            soreThroat: false,
            runnyNose: false,
            bodyAches: true,
            sweating: false,
            createdAt: new Date('2024-01-22').toISOString(),
            updatedAt: new Date('2024-01-22').toISOString(),
        },
        {
            diseaseName: 'Anxiety Attack',
            medicineMeasures: 'Practice deep breathing. Remove from stressful environment. Consider counseling.',
            fever: false,
            headache: true,
            cough: false,
            nausea: false,
            vomiting: false,
            chestPain: true,
            breathlessness: true,
            abdominalPain: false,
            soreThroat: false,
            runnyNose: false,
            bodyAches: false,
            sweating: true,
            createdAt: new Date('2024-01-25').toISOString(),
            updatedAt: new Date('2024-01-25').toISOString(),
        },
        {
            diseaseName: 'Migraine',
            medicineMeasures: 'Dark quiet room. Pain relievers. Apply cold compress to head.',
            fever: false,
            headache: true,
            cough: false,
            nausea: true,
            vomiting: true,
            chestPain: false,
            breathlessness: false,
            abdominalPain: false,
            soreThroat: false,
            runnyNose: false,
            bodyAches: true,
            sweating: false,
            createdAt: new Date('2024-01-28').toISOString(),
            updatedAt: new Date('2024-01-28').toISOString(),
        }
    ];

    await db.insert(diseases).values(sampleDiseases);
    
    console.log('✅ Diseases seeder completed successfully');
}

main().catch((error) => {
    console.error('❌ Seeder failed:', error);
});